---
version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: 'db'
    environment:
      MYSQL_DATABASE: redirects
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./test/mysql-data:/var/lib/mysql