---
version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: 'db'
    environment:
      MYSQL_DATABASE: redirects
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
  app:
    build:
      context: ./
    volumes:
      - "./:/go"
    container_name: url_shortener
    restart: always
    environment:
      HOSTNAME: localhost
      SCHEME: http
      PORT: "3000"
    ports:
      - "3000:3000"
    depends_on:
      - db